backend:
  name: github
  repo: Safdarali713/safdarali713.github.io
  branch: main
  base_url: https://decap-proxy.decap-proxy-safdar-2026.workers.dev
  auth_endpoint: /auth

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
